<a href="https://colab.research.google.com/github/mk7890/Machine-Learning-II/blob/main/ML2_NeuraNetworks_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# !pip install tensorflow
# !pip install --upgrade keras

# Libraries

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import tensorflow as tf
import keras

In [4]:
print(f"tensorflow version: {tf.__version__}")
print(f"keras version {keras.__version__}")

tensorflow version: 2.17.1
keras version 3.8.0


# Load Dataset

In [5]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0

# Build a machine learning model
Build a tf.keras.Sequential model:

In [6]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [7]:
predictions = model(x_train[:1]).numpy()
predictions

array([[-0.09069672, -0.03890756, -0.12090513,  0.7525129 ,  0.30860126,
        -0.26329035, -0.39538553, -0.0989765 , -0.49409962,  0.3403374 ]],
      dtype=float32)

In [8]:
tf.nn.softmax(predictions).numpy()

array([[0.08609211, 0.09066822, 0.0835303 , 0.200062  , 0.12834421,
        0.07244474, 0.06348026, 0.08538223, 0.05751322, 0.13248268]],
      dtype=float32)

In [9]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [10]:
loss_fn(y_train[:1], predictions).numpy()

2.624931

In [11]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])

# Train and evaluate your model

In [12]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.8610 - loss: 0.4808
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 9s 5ms/step - accuracy: 0.9553 - loss: 0.1477
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - accuracy: 0.9677 - loss: 0.1087
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9749 - loss: 0.0841
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - accuracy: 0.9764 - loss: 0.0742


In [13]:
model.evaluate(x_test,  y_test, verbose=2)

313/313 - 1s - 2ms/step - accuracy: 0.9773 - loss: 0.0704


[0.07035411149263382, 0.9772999882698059]

In [14]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [15]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[1.9469363e-08, 3.7422732e-09, 1.5313002e-06, 9.9650115e-06,
        6.0538965e-12, 1.1902132e-08, 7.3758962e-16, 9.9998796e-01,
        2.1916658e-07, 2.3417140e-07],
       [2.5970001e-08, 1.5371914e-02, 9.8434258e-01, 2.5194383e-04,
        4.0960040e-14, 3.3167002e-05, 5.5405572e-08, 1.4228829e-13,
        4.0203932e-07, 3.4716785e-12],
       [2.9123635e-07, 9.9944764e-01, 4.7234291e-05, 2.6581240e-06,
        5.6910645e-05, 4.6741326e-07, 1.4665933e-05, 3.4539143e-04,
        8.4364023e-05, 3.3531714e-07],
       [9.9891460e-01, 7.3379411e-08, 1.0701964e-03, 3.4111531e-07,
        1.6283947e-06, 4.6322161e-06, 4.2480369e-06, 4.5770980e-07,
        2.7275979e-07, 3.5155988e-06],
       [3.0390850e-06, 5.2184106e-09, 3.9357255e-05, 2.2890713e-08,
        9.9526441e-01, 4.0068105e-07, 8.9736241e-06, 6.0888102e-05,
        3.7383379e-06, 4.6191448e-03]], dtype=float32)>